<?xml version="1.0"?>
<!DOCTYPE rooms[
    <!ELEMENT rooms (room*)>    
        <!ELEMENT room (id, name, s0, s1, s2, s3, s4, s5)>
            <!ELEMENT id (#PCDATA)>
            <!ELEMENT name (#PCDATA)>
            <!ELEMENT s0 (#PCDATA)>
            <!ELEMENT s1 (#PCDATA)>
            <!ELEMENT s2 (#PCDATA)>
            <!ELEMENT s3 (#PCDATA)>
            <!ELEMENT s4 (#PCDATA)>
            <!ELEMENT s5 (#PCDATA)>
]>

<rooms>
    
    <room>
        <id>sal</id>
        <name>Saltö</name>
        <s0>No Presentation</s0>
        <s1>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#secm&quot; data-role=&quot;none&quot;&gt;Securing mobile applications&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#ulfl&quot; data-role=&quot;none&quot;&gt;Ulf Larson&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 1-sal&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s1>
        <s2>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#sana&quot; data-role=&quot;none&quot;&gt;Så når du ut med din app&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#jonatan&quot; data-role=&quot;none&quot;&gt;Jonatan Redvik&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 2-sal&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s2>
        <s3>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#unmob&quot; data-role=&quot;none&quot;&gt;Understanding mobile design patterns&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#erikl&quot; data-role=&quot;none&quot;&gt;Erik Larsson&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 3-sal&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s3>
        <s4>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#mobweb&quot; data-role=&quot;none&quot;&gt;Mobil webbutveckling med HTML5, CSS3 och JavaScript&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#perd&quot; data-role=&quot;none&quot;&gt;Per Daleskog&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 4-sal&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s4>
        <s5>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#appres&quot; data-role=&quot;none&quot;&gt;En applikations resa från Windows Phone till Windows 8&lt;/a&gt;&lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#andhammar&quot; data-role=&quot;none&quot;&gt;Andreas Hammar&lt;/a&gt; &#38; &lt;br /&gt; &lt;a class=&quot;speakerLink&quot; href=&quot;#hakan&quot; data-role=&quot;none&quot;&gt;Håkan Reis&lt;/a&gt;&lt;br /&gt;&lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 5-sal&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s5>
    </room>

    <room>
        <id>ell</id>
        <name>Ellös</name>
        <s0>No Presentation</s0>
        <!--<s1>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#spelapp&quot; data-role=&quot;none&quot;&gt;Spel och apputveckling Cross plattform&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#andreask&quot; data-role=&quot;none&quot;&gt;Andreas Kviby&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 1-ell&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s1>-->
        
        <s1>No Presentation</s1>

        <s2>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#mdesign&quot; data-role=&quot;none&quot;&gt;Skapa snygga appar i Metro design&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#danwei&quot; data-role=&quot;none&quot;&gt;Danwei Tran Luciani&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 2-ell&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s2>
        <s3>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#wpbest&quot; data-role=&quot;none&quot;&gt;Windows Phone Development - Best Practices&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#johanl&quot; data-role=&quot;none&quot;&gt;Johan Lindfors&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 3-ell&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s3>
        <s4>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#gamedev&quot; data-role=&quot;none&quot;&gt;Game Development with Unity for Mobile Devices&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#johan&quot; data-role=&quot;none&quot;&gt;Johan Sanneblad&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 4-ell&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s4>
        <!--<s5>No Presentation</s5>-->
        <s5>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#vinnare&quot; data-role=&quot;none&quot;&gt;Bli en vinnare på företagsmarknaden med dina appar!&lt;/a&gt;&lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#mhansson&quot; data-role=&quot;none&quot;&gt;Mattias Hansson&lt;/a&gt;&lt;br /&gt;&lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 5-ell&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s5>
    </room>

    <room>
        <id>bra</id>
        <name>Brännö</name>
        <s0>
            Keynote&lt;br /&gt;&lt;a class=&quot;subjectLink&quot; href=&quot;#top11&quot; data-role=&quot;none&quot;&gt;Top 11 Trends for Enterprise Mobile&lt;/a&gt;&lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#erwan&quot; data-role=&quot;none&quot;&gt;Erwan Paccard&lt;/a&gt;&lt;br /&gt;&lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 0-bra&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s0>
        <s1>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#mapp&quot; data-role=&quot;none&quot;&gt;Mobile app vs. mobile site&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#patrik&quot; data-role=&quot;none&quot;&gt;Patrik Malmquist&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 1-bra&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s1>
        <s2>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#anapp&quot; data-role=&quot;none&quot;&gt;An app is not enough&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#joakim&quot; data-role=&quot;none&quot;&gt;Joakim Kemeny&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 2-bra&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s2>
        <s3>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#tackand&quot; data-role=&quot;none&quot;&gt;Tackling Android fragmentation&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#glenn&quot; data-role=&quot;none&quot;&gt;Glenn Richard Bech&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 3-bra&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s3>
        <s4>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#lowl&quot; data-role=&quot;none&quot;&gt;Low Latency Messaging for Mobile Apps - Or When HTTP and Push Messages Are Simply Not Enough&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#henriks&quot; data-role=&quot;none&quot;&gt;Henrik Sjöstrand&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 4-bra&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s4>
        <s5>No Presentation</s5>
    </room>

    <room>
        <id>asp</id>
        <name>Asperö</name>
        <s0>No Presentation</s0>
        <s1>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#sensa&quot; data-role=&quot;none&quot;&gt;Cross-platform development with HTML5 and Sencha Touch&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#conny&quot; data-role=&quot;none&quot;&gt;Conny Svensson&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 1-asp&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s1>
        <s2>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#soyou&quot; data-role=&quot;none&quot;&gt;So you have the greatest idea for the Next Big Hit Windows Phone Game?&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#mattiasl&quot; data-role=&quot;none&quot;&gt;Mattias Larsson&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 2-asp&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s2>
        <s3>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#ending&quot; data-role=&quot;none&quot;&gt;Ending the Web Versus Native Debate&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#kevin&quot; data-role=&quot;none&quot;&gt;Kevin Whinnery&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 3-asp&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s3>
        <s4>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#intwin8&quot; data-role=&quot;none&quot;&gt;Introduktion till Windows 8 och Metro style apps&lt;/a&gt;&lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#dag&quot; data-role=&quot;none&quot;&gt;Dag König&lt;/a&gt; &#38; &lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#danwei&quot; data-role=&quot;none&quot;&gt;Danwei Tran Luciani&lt;/a&gt;&lt;br /&gt;&lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 4-asp&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s4>
        <s5>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#titan&quot; data-role=&quot;none&quot;&gt;Titanium Mobile – A brief overview and introduction to a cross platform framework&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#jorgen&quot; data-role=&quot;none&quot;&gt;Jörgen Buder&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 5-asp&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s5>
    </room>

    <room>
        <id>kon</id>
        <name>Kongressalen</name>
        <s0>No Presentation</s0>
        <s1>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#wpdev&quot; data-role=&quot;none&quot;&gt;Windows Phone för utvecklare&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#dag&quot; data-role=&quot;none&quot;&gt;Dag König&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 1-kon&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s1>
        <s2>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#amashups&quot; data-role=&quot;none&quot;&gt;Having fun with Android mashups&lt;/a&gt;&lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#par&quot; data-role=&quot;none&quot;>Pär Sikö&lt;/a&gt; &#38; &lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#martin&quot; data-role=&quot;none&quot;&gt;Martin Gunnarsson&lt;/a&gt;&lt;br /&gt;&lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 2-kon&quot;data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s2>
        <s3>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#mobcross&quot; data-role=&quot;none&quot;&gt;Mobile cross-platform development with JQuery Mobile&lt;/a&gt;&lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#jorgenb&quot; data-role=&quot;none&quot;&gt;Jörgen Bengtsson&lt;/a&gt; &#38; &lt;br /&gt;&lt;a class=&quot;speakerLink&quot; href=&quot;#johanh&quot; data-role=&quot;none&quot;&gt;Johan Holm&lt;/a&gt;&lt;br /&gt;&lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 3-kon&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s3>
        <s4>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#phonegap&quot; data-role=&quot;none&quot;&gt;Getting Started with PhoneGap&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#mihai&quot; data-role=&quot;none&quot;&gt;Mihai Corlan&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 4-kon&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s4>
        <s5>
            &lt;a class=&quot;subjectLink&quot; href=&quot;#momo&quot; data-role=&quot;none&quot;&gt;Modern Mobile Web Design with Maquetta and Dojo/Dojo Mobile&lt;/a&gt;
            &lt;br /&gt;
            &lt;a class=&quot;speakerLink&quot; href=&quot;#matthew&quot; data-role=&quot;none&quot;&gt;Matthew Perrins&lt;/a&gt;
            &lt;br /&gt;
            &lt;a href=&quot;#dialog&quot; data-transition=&quot;none&quot; data-rel=&quot;dialog&quot; id=&quot;SESSION 5-kon&quot; data-inline=&quot;true&quot; data-mini=&quot;true&quot;&gt;CHOOSE&lt;/a&gt;
        </s5>
    </room>
    
</rooms>