<?xml version="1.0"?>
<!DOCTYPE contributors [
    <!ELEMENT contributors (contributor*)>
    <!ELEMENT contributor (id, company, info)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT company (#PCDATA)>
    <!ELEMENT info (#PCDATA)>
]>


<contributors>
    
    <contributor>
        <id>squeed</id>
        <company>Squeed</company>
        <info>
            &lt;a href=&quot;http://www.squeed.se/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/squeed.png&quot; alt=&quot;squeed&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;Squeeders jobbar med arkitekturfrågor, coaching, mentorskap, utbildningar, systemutveckling, metoder mm. Vi är experter på Java, Microsoft .Net och open source. Som Microsoft MVP och Insider har vi bra relation med Microsoft samt vetskap och kunskap om det kommande och senaste från Microsoft .Net.&lt;br /&gt;

        </info>
    </contributor>

    <contributor>
        <id>javaforum</id>
        <company>Javaforum.se</company>
        <info>
            &lt;a href=&quot;http://www.javaforum.se&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/javaforum.png&quot; alt=&quot;javaforum&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;Javaforum is a Swedish Java-community supporting Java developers by arranging meetings, seminars and conferences. More information about Javaforum and upcoming meetings can be found at &lt;a href=&quot;http://www.javaforum.se&quot; target=&quot;_blank&quot;>www.jforum.se&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Javaforum hosts meetings in Stockholm, Göteborg, Malmö and Umeå.&lt;br /&gt;

        </info>
    </contributor>

    <contributor>
        <id>nforum</id>
        <company>nforum.se</company>
        <info>
            &lt;a href=&quot;http://www.nforum.se/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/nforum.png&quot; alt=&quot;nforum&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;nforum är en svensk .net-community i Göteborg med syfte att stödja svenska .net-utvecklare genom regelbundna möten med intressanta seminarier och mingel.&lt;br /&gt;
				&lt;br /&gt;nforum har ett brett samarbete med många andra fristående communities så som Swenug och Javaforum.&lt;br /&gt;
 				&lt;br /&gt;Vill du ställa upp som talare eller tipsa om talare eller kanske till och med vill sponsra ett event i framtiden så är du välkommen att kontakta oss med just dina ideer.  Allt är välkommet.&lt;br /&gt;
 				&lt;br /&gt;Vid frågor tveka inte att kontakta oss via: nforum (a) squeed.com&lt;br /&gt;
 				&lt;br /&gt;Mvh nforum &lt;a href=&quot;http://www.nforum.se/&quot; target=&quot;_blank&quot;>www.nforum.se&lt;/a&gt;&lt;br /&gt; 
        </info>
    </contributor>

    <contributor>
        <id>cocoa</id>
        <company>CocoaHeads</company>
        <info>
            &lt;a href=&quot;http://www.meetup.com/cocoaheads-goteborg/&quot;target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/cocoahead.png&quot;alt=&quot;cocoa&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;CocoaHeads is a group devoted to discussion of Apple Computer’s Cocoa &lt;a href=&quot;https://developer.apple.com/technologies/mac/cocoa.html&quot; target=&quot;_blank&quot;>Framework&lt;/a&gt; for programming on MacOS X (including the iPhone). During monthly meetings, members present on their projects and offer tutorials on various programming topics.&lt;br /&gt;
            &lt;br /&gt;Read more about CocoaHeads on our &lt;a href=&quot;http://www.meetup.com/cocoaheads-goteborg/&quot; target=&quot;_blank&quot;>website&lt;/a&gt;&lt;br /&gt;

        </info>
    </contributor>

    <contributor>
        <id>gomobile</id>
        <company>go mobile</company>
        <info>
            &lt;a href=&quot;http://www.go-mobile.se/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/gomobile.jpg&quot; alt=&quot;gomobile&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;go mobile is a non profit organisation targeted to grow the mobile industry in the Gothenburg region. The organisation will help start-ups and take small companies to the next level through networking, mentorship, global PR and VC funding from local and international investors.&lt;br /&gt;
            &lt;br /&gt;&lt;h2&gt;Mobile and Mobility&lt;/h2&gt;&lt;br /&gt;
            &lt;br /&gt;Mobile is the state of being in motion and is a generic term describing the ability to use technology on the move, and often refer to access and create information from connected, portable, networked communication device.&lt;br /&gt;
            &lt;br /&gt;Mobile is the core of the individual and the organisations communication, digital consumption and lifestyle at home and at work. Regardless of information carrier (desktop, laptop, tablet, phone, console or TV we are always online, available and expect the same experience regardless of platform.&lt;br /&gt;
            &lt;br /&gt;&lt;a href=&quot;http://www.linkedin.com/groups/go-mobile-3088466?gid=3088466&quot; target=&quot;_blank&quot;>go mobile on LinkedIn&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;During the spring 2010 a group was created on LinkedIn for professionals active in the mobile industry with a relationship to Gothenburg in some way. No marketing was needed, the logo go:mobile spoke its own words.&lt;br /&gt;
            &lt;br /&gt;Quite soon professionals from all spectrum of the mobile industry joined the group. We are now about to embark on the next level an show that Gothenburg will go mobile.&lt;br /&gt;
        </info>
    </contributor>

    <contributor>
        <id>brg</id>
        <company>BRG</company>
        <info>
            &lt;a href=&quot;http://www.businessregion.se/index.html&quot;target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/brg.jpg&quot; alt=&quot;brg&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;Business Region Göteborg AB (BRG) är ett helägt, icke-vinstdrivande dotterbolag till Göteborgs Kommunala Förvaltnings AB, vilket i sin tur är helägt av Göteborgs Stad. Business Region Göteborg arbetar för ökad tillväxt och sysselsättning i Göteborgsregionen. Företaget hjälper såväl beﬁntliga företag som nyetableringar i deras ambitioner att växa. Business Region Göteborg driver bland annat ett antal branschutvecklande &lt;a href=&quot;http://www.businessregion.se/huvudmeny/affarsomraden.4.42d895c410678a3d6138000256.html&quot; target=&quot;_blank&quot;>projekt&lt;/a&gt; som syftar till att bidra till tillväxten på strategiska områden. Fokus ligger på de branscher som är starka inom regionen. Business Region Göteborg arbetar även med &lt;a href=&quot;http://www.businessregion.se/huvudmeny/foretagsutveckling.4.42d895c410678a3d6138000449.html&quot; target=&quot;_blank&quot;>företagsutveckling&lt;/a&gt;, framför allt i projektet &lt;a href=&quot;http://www.businessregion.se/expeditionframat&quot; target=&quot;_blank&quot;>Expedition Framåt&lt;/a&gt;.&lt;br /&gt;
            &lt;br /&gt;Business Region Göteborg har för närvarande cirka 90 medarbetare och arbetar tillsammans med de &lt;a href=&quot;http://www.businessregion.se/huvudmeny/omoss/businessregiongoteborgidinkommun.4.42d895c410678a3d6138000465.html&quot; target=&quot;_blank&quot;>näringslivsansvariga&lt;/a&gt; och företagen i de &lt;a href=&quot;http://www.businessregion.se/huvudmeny/omoss/regionens13kommuner.4.42d895c410678a3d6138000852.html&quot; target=&quot;_blank&quot;>13 kommuner&lt;/a&gt; som utgör Göteborgsregionen. VD för verksamheten är Patrik Andersson, styrelseordförande är Anneli Hulthén.&lt;br /&gt;

        </info>
    </contributor>

    <contributor>
        <id>datafor</id>
        <company>Dataföreningen</company>
        <info>
            &lt;a href=&quot;http://www.dfs.se/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/datafor.png&quot; alt=&quot;datafor&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;Dataföreningen är det självklara valet för den som vill följa branschen. Medlemsavgiften inkluderar prenumeration på Computer Sweden All Inclusive OCH MYCKET MER.&lt;br /&gt;
            &lt;br /&gt;Under trevliga och kostnadseffektiva former bygger vi relationer mellan både individer och organisationer genom nätverksträffar, seminarier och konferenser.&lt;br /&gt;
            &lt;br /&gt;Läs mer om oss:&lt;br /&gt;

            &lt;br /&gt;&lt;a href=&quot;https://www.dfs.se/vastra/bli_medlem_fore_midsommar&quot; target=&quot;_blank&quot;>www.dfs.se/vastra&lt;/a&gt;&lt;br /&gt;
        </info>
    </contributor>

</contributors>
