<?xml version="1.0"?>
<!DOCTYPE speakers [
<!ELEMENT speakers (speaker*)>
    <!ELEMENT speaker (id, fname,lname, info)>
        <!ELEMENT id	(#PCDATA)>
        <!ELEMENT fname (#PCDATA)>
        <!ELEMENT lname (#PCDATA)>
        <!ELEMENT info (#PCDATA)>
]>

<speakers>
    
    <speaker>
		<id>mihai</id>
        <fname>Mihai</fname>
        <lname>Corlan</lname>
        <info>
            
            &lt;img src=&quot;images/mihai.jpg&quot; alt=&quot;mihai&quot;/&gt;&lt;br /&gt;             
            &lt;br /&gt;Mihai Corlan's presentations:&lt;br /&gt; &lt;a href=&quot;#phonegap&quot;&gt;Getting Started with PhoneGap&lt;/a&gt; &lt;br /&gt;
            
            &lt;br /&gt;Mihai Corlan is a worldwide web developer evangelist at Adobe focusing on web technologies. He travels around the world speaking at conferences and meeting developers and customers. Prior to joining Adobe, Mihai was a senior web developer with InterAKT Online (acquired by Adobe in 2006), where he worked on web products such as e-shops, newsletters, and surveys or on RAD tools for web developers. He built web applications and frameworks, desktop software, and rich internet applications using technologies like: PHP, ColdFusion, Java, HTML/CSS, JavaScript, AJAX, ActionScript/Flex and relational databases. He believes that in the future more people will interact with software and consume Internet using smartphones and tablets. And the user experience plays an important role in all these new things that are coming because we’ve come a long way since black screens with tiny white letters. Since 2008 he’s been writing about rich internet applications and mobile development at &lt;a href=&quot;http://www.corlan.org/&quot; target=&quot;_blank&quot;>corlan.org&lt;/a&gt;&lt;br /&gt; 
            &lt;br /&gt;You can follow him on Twitter  &lt;a href=&quot;http://twitter.com/mcorlan&quot; target=&quot;_blank&quot;&gt;http://twitter.com/mcorlan&lt;/a&gt;
        </info>
    </speaker>
    
    <speaker>
		<id>patrik</id>
        <fname>Patrik</fname>
        <lname>Malmquist</lname>
        <info>
            &lt;img src=&quot;images/patrik.jpg&quot; alt=&quot;patrik&quot;/&gt;&lt;br /&gt;  
            &lt;br /&gt;Patrik Malmquist's presentation:&lt;br /&gt; &lt;a href=&quot;#mapp&quot;&gt;Mobile app vs. mobile site&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Patrik Malmquist is a tech loving geek that left development for strategy, project management and software development organization. In his role as Enterprise Mobility Manager for &lt;a href=&quot;http://www.sigma.se/&quot; target=&quot;_blank&quot;&gt;Sigma&lt;/a&gt; he works with architecture and solution selling within mobile and web solutions. Between 2005 and 2011 he was the software development manager for &lt;a href=&quot;https://www.minpension.se/&quot; target=&quot;_blank&quot;&gt;www.minpension.se&lt;/a&gt; and project manager for pension prognosis tools for web and mobile solutions for &lt;a href=&quot;http://www.pensionsmyndigheten.se/&quot; target=&quot;_blank&quot;&gt;the Swedish Pensions Agency&lt;/a&gt;. You can follow him at his personal blog &lt;a href=&quot;http://www.applitude.se&quot; target=&quot;_blank&quot;&gt;http://www.applitude.se&lt;/a&gt;  that focuses on leading productive software development teams and on his &lt;a href=&quot;http://blogg.sigma.se/en/Mobility/Patrik-Malmquist&quot; target=&quot;_blank&quot;&gt;Sigma blog&lt;/a&gt;  that focuses on the mobile work life.
		</info>
    </speaker>
    
    <speaker>
		<id>dag</id>
        <fname>Dag</fname>
        <lname>König</lname>
        <info>
            &lt;img src=&quot;images/dag.jpg&quot; alt=&quot;dag&quot;/&gt;&lt;br /&gt;  
            &lt;br /&gt;Dag König's presentation:&lt;br /&gt; &lt;a href=&quot;#intwin8&quot; >Introduktion till Windows 8 och Metro Style Apps&lt;/a&gt;&lt;br /&gt;
            &lt;a href=&quot;#wpdev&quot; >Windows Phone för utvecklare&lt;/a&gt;
            &lt;br /&gt;Dag König, teknisk evangelist på Microsoft. Han är Windows Phone Champ i Sverige, vilket innebär att han jobbar med partners och alla andra som är intresserade av att utveckla appar för Windows Phone. Dag har själv varit med och utvecklar en hel bunt av appar själv. Följ honom på Twitter via &lt;a href=&quot;http://twitter.com/buzzfrog&quot; target=&quot;_blank&quot;>@buzzfrog&lt;/a&gt;.
		</info>
    </speaker>
    
    <speaker>
		<id>andhammar</id>
        <fname>Andeas</fname>
        <lname>Hammar</lname>
        <info>
            &lt;img src=&quot;images/andreashammar.png&quot; alt=&quot;andhammar&quot;/&gt;&lt;br /&gt;  
            &lt;br /&gt;Andreas Hammars's presentation:&lt;br /&gt; &lt;a href=&quot;#appres&quot; >En applikations resa från Windows Phone till Windows 8&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Andreas är en utvecklare med intresse inom allt från agila metoder till små tekniska detaljer. Sedan millenieskiftet har han gjort klientutveckling på Microsofts plattform och fokuserar nu på Windows Phone. Sedan 2010 har Andreas varit en del av Jayway’s Windows Phone-team och levererat flertalet appar, hållit kurser och talat om Windows Phone 7 på seminarier.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>danwei</id>
        <fname>Danwei</fname>
        <lname>Tran Luciani</lname>
		<info>&lt;img src=&quot;images/danwei.jpg&quot; alt=&quot;danwei&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Danwei Tran Luciani's presentation:&lt;br /&gt; &lt;a href=&quot;#mdesign&quot; >Skapa snygga appar i Metro design&lt;/a&gt;&lt;br /&gt;
            &lt;br&gt;&lt;a href=&quot;#intwin8&quot; >Introduktion till Windows 8 och Metro style apps&lt;/a&gt;&lt;br&gt;
            &lt;br /&gt;Danwei Tran Luciani är teknisk evangelist på Microsoft. Hennes nuvarande fokusområden är Metro-design, HTML5 och nästa version av Windows. Hon gillar att samla Xbox achievements, att geocacha, och är svag för kaniner. Följ hennes tweets på &lt;a href=&quot;http://twitter.com/danweitran&quot; target=&quot;_blank&quot;>@danweitran&lt;/a&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>par</id>
        <fname>Pär</fname>
        <lname>Sikö</lname>
        <info>&lt;img src=&quot;images/par.png&quot; alt=&quot;par&quot;/&gt;&lt;br&gt;
            &lt;br /&gt;Pär Sikö's presentation:&lt;br /&gt; &lt;a href=&quot;#amashups&quot; >Having fun with Android mashups&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Pär is a java developer, working primarily with Android but with a long and happy history that includes J2ME, Swing and JavaFX.&lt;br /&gt; 
            &lt;br /&gt;He’s been working with Java since it’s inception and tried everything from architecture and large enterprise systems to mobile devices.&lt;br /&gt; 
            &lt;br /&gt;As a developer Pär is curious and thorough and knows the importance of pixels and colors. Curious to learn new things, growing as a human being in the process, and happy to teach and inspire others about it. Thorough to ensure that the quality is on par with expectations and, perhaps most importantly, to really understand something makes it so much easier and fun to work with. Pixels and Colors have never been as important as it is today, everything is measured by it’s looks, and Pär’s focus on making beautiful applications is a deliberate strategy that has paid off numerous times.&lt;br /&gt; 
            &lt;br /&gt;Pär has been a busy speaker for the last couple of years, presenting on the international stage as well as on Swedish conferences.&lt;br /&gt; 
            &lt;br /&gt;He was awarded with a ‘JavaOne Rock Star’ for his presentation in San Francisco 2011. For Pär, the key success factor in a presentation is mixing good content with a big portion of humour and he wishes that more people would dare to step away from boring bullet lists and do something new and creative when presenting.
		</info>
    </speaker>
    
    <speaker>
		<id>martin</id>
        <fname>Martin</fname>
        <lname>Gunnarsson</lname>
        <info>&lt;img src=&quot;images/martin.png&quot; alt=&quot;martin&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Martin Gunnarsson's presentation:&lt;br /&gt; &lt;a href=&quot;#amashups&quot; >Having fun with Android mashups&lt;/a&gt;&lt;br /&gt; 
            &lt;br /&gt;Great programmers are usually lousy designers, and vice versa, but Martin is one of those rare crossbreeds who can handle both. Graphics programming and GUI design suits him particularly well, but being a true perfectionist, heʼs rarely satisfied with the results of his own work. Martin has worked with many different client side frameworks the last few years, including Swing, JavaFX, Android, Javascript and iOS.
		</info>
    </speaker>
    
    <speaker>
		<id>johan</id>
        <fname>Johan</fname>
        <lname>Sanneblad</lname>
        <info>&lt;img src=&quot;images/Johan.jpg&quot; alt=&quot;johan&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Johan Sanneblad's presentation:&lt;br /&gt; &lt;a href=&quot;#gamedev&quot; >Game Development with Unity for Mobile Devices&lt;/a&gt;&lt;br&gt;
            &lt;br /&gt;Johan Sanneblad works as a consultant manager at HiQ. Johan has a Ph.D in mobile IT where he designed and implemented advanced cross-platform game development tools for companies such as Nokia and Sony Online Entertainment. Johan has worked at HiQ since 2005 in various roles including both developer and project leader, for clients such as Ericsson, HP, SJ, Skype, Sony Ericsson, Telia, Volvo Cars, Volvo Trucks, and many others. Johan has a genuine game interest, and created the game “Tomten” in Unity together with his wife Helena in his spare time during autumn 2011. The game was launched on December 13 and reached #13 in most downloaded games in the Swedish App Store in December.
		</info>
    </speaker>
    
    <speaker>
		<id>glenn</id>
        <fname>Glenn</fname>
        <lname>Richard Bech</lname>
        <info>&lt;img src=&quot;images/glenn.jpg&quot; alt=&quot;glenn&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Glenn Richard Bech's presentation:&lt;br /&gt; &lt;a href=&quot;#tackand&quot; >Tackling Android fragmentation&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Glenn Bech manages the Inmeta Consulting Java team and works hands-on in software development projects. He has developed software on the Java platform , mainly server side. for the Banking and insurance industry for the last ten years. For Glenn, as for many a developer, it all started 20 years ago with “Poke 53281,0″ on the Commodore 64. Since then, he has programmed a wide range of languages. The first of his now several Android applications was published on the Android market in february 2011. He saw the fun and potential in tablet devices and was quick to embrace Honeycomb. He is now a very passionate Android developer. Glenn is the co-founder of the Norwegian software comminity &lt;a href=&quot;http://www.baksia.org/&quot; target=&quot;_blank&quot;>Baksia&lt;/a&gt; that is non-profit and promotes everything scalable and backend related.
		</info>
    </speaker>
    
    <speaker>
		<id>hakan</id>
        <fname>Håkan</fname>
        <lname>Reis</lname>
        <info>&lt;img src=&quot;images/hakan_reis.jpg&quot; alt=&quot;hakan&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Håkan Reis presentation:&lt;br /&gt; &lt;a href=&quot;#appres&quot; >En applikations resa från Windows Phone till Windows 8&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Håkan har många års erfarenhet inom .NET-utveckling och har de senaste åren haft allt mer fokus på UX. Sedan MIX 2010 har Håkan arbetat med Windows Phone 7 och byggt upp en fantastisk känsla för hur Metro design ska uttryckas som han nu tar med sig till Windows 8.&lt;br /&gt; 
            
            &lt;br /&gt;&lt;a href=&quot;http://blog.jayway.com/author/hakanreis/&quot; target=&quot;_blank&quot;>Blogg http://blog.jayway.com/author/hakanreis/&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Twitter: &lt;a href=&quot;http://twitter.com/#!/haqwin&quot; target=&quot;_blank&quot;>@haqwin&lt;/a&gt;&lt;br /&gt; 
		</info>
    </speaker>
    
    <speaker>
		<id>johanl</id>
        <fname>Johan</fname>
        <lname>Lindfors</lname>
        <info>&lt;img src=&quot;images/johanl.jpg&quot; alt=&quot;johanl&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Johan Lindfors presentation:&lt;br /&gt; &lt;a href=&quot;#wpbest&quot; >Windows Phone Development - Best Practices&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Johan Lindfors has been working with Windows Phone since the early days of Windows Mobile and are often speaking about the platform at various events. Johan has founded the company Coderox, currently focused on Windows Phone 7 and Windows 8 with various customers and engagements, some leveraging Silverlight/HTML5 and others using XNA/DirectX. Before Coderox, he worked at Microsoft for almost 13 years, and have also been the head of development at Infozone.&lt;br /&gt; 
		</info>
    </speaker>
    
    <speaker>
		<id>matthew</id>
        <fname>Matthew</fname>
        <lname>Perrins</lname>
        <info>&lt;img src=&quot;images/matthew.jpg&quot; alt=&quot;matthew&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Matthew Perrins presentation:&lt;br /&gt; &lt;a href=&quot;#momo&quot; >Modern Mobile Web Design with Maquetta and Dojo/Dojo Mobile&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Matthew Perrins is an Executive IT Specialist for IBM Software Group Lab Services based at the world famous Hursley Development Lab in the UK. He leads the WebSphere Mobile Business Solutions team for Europe which is focused on delivering first of kind Web 2.0 and Mobile solutions for IBM Clients. He has worked for IBM since 1989 and has spent the last 15 years working with Java and enterprise solutions with WebSphere and J2EE.&lt;br /&gt;
            &lt;br /&gt;Matthews expertise in end user solutions allow him to focused on architecting, designing and developing solutions that operate between the end user and the edge of an SOA. This involves Web 2.0, Ajax at one end of the spectrum through to Portal, Business Space traditional Web Technology’s in the middle and then right through to Rich Client technology’s that operating on the Desktop and Device like PhoneGap, Eclipse RCP and Lotus Expeditor, Notes and Sametime. His skills are focused on all the User Interface technologies that are strategic to IBM and our customers.&lt;br /&gt;
            &lt;br /&gt;Matthew is one of the leading practitioners of Web 2.0 for IBM and has lead a number of key projects that have helped shape a lot of best practices for Web 2.0 solution design and delivery.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>ulfl</id>
        <fname>Ulf</fname>
        <lname>Larsson</lname>
        <info>&lt;img src=&quot;images/ulfl.jpg&quot; alt=&quot;ulfl&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Ulf Larson's presentation:&lt;br /&gt; &lt;a href=&quot;#secm&quot; >Securing mobile applications&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Ulf Larson is currently employed at Adecco IT Konsult as an information security consultant. His interests lays within the fields of application security, vulnerability analysis, and threat and risk modelling. Ulf holds a Ph.D. from Chalmers University and is one of three co-leaders for OWASP’s Gothenburg chapter.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>kevin</id>
        <fname>Kevin</fname>
        <lname>Whinnery</lname>
        <info>&lt;img src=&quot;images/kevin.jpg&quot; alt=&quot;ulfl&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Kevin Whinnery's presentation:&lt;br /&gt; &lt;a href=&quot;#ending&quot; >Ending the Web Versus Native Debate&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Kevin is probably the one that knows most about Titanium Mobile as he where there when it was invented, he has gone through garage startup to the number one framework for cross platform native mobile app development. He is by far the closest to the core of Titanium you can get and he gives valuable latest perspectives on the mobile market as well as in depth code techniques as he talks. Meet Kevin Whinnery, evangelist, coder and Director of Developer Relations.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>joakim</id>
        <fname>Joakim</fname>
        <lname>Kemeny</lname>
        <info>&lt;img src=&quot;images/joakim.jpg&quot; alt=&quot;joakim&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Joakim Kemeny's presentation:&lt;br /&gt; &lt;a href=&quot;#anapp&quot; >An app is not enough&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Joakim Kemeny is working as a consultant and he helps his customers by creating great user experiences for web applications, mobile devices and public web sites. His interests spans from creating a solid web architecture that can support a high performance web application to getting his hands dirty in CSS rules that make Internet Explorer shine.&lt;br /&gt;
            &lt;br /&gt;Joakim has been making web sites since 1996 so when he started sharing his thoughts as a public speaker it was natural to focus on the different things that makes a great front end developer.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>conny</id>
        <fname>Conny</fname>
        <lname>Svensson</lname>
        <info>&lt;img src=&quot;images/conny.png&quot; alt=&quot;conny&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Conny Svensson's presentation:&lt;br /&gt; &lt;a href=&quot;#sensa&quot; >Cross-platform development with HTML5 and Sencha Touch&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Conny är en driven arkitekt och innovatör med över 15 års branscherfarenhet inom IT. Han spänner över ett brett fält från interaktionsdesign och datamodellering till ramverk och analyser.&lt;br /&gt;
            &lt;br /&gt;Conny är anställd på Logica som arkitekt och strateg inom mobilitet, med inriktning mot kreativa lösningar för smartphones och pekplattor inom offentlig sektor, industri och även privata marknaden. Där har han jobbat med att ta fram appar och tjänster, lösnings och systemarkitektur samt drivit strategi och visionsarbete för kunder. Conny lever efter devisen: Det svåra är att göra det enkelt!&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>jorgen</id>
        <fname>Jörgen</fname>
        <lname>Buder</lname>
        <info>&lt;img src=&quot;images/jorgen.jpg&quot; alt=&quot;jorgen&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Jörgen Buder's presentation:&lt;br /&gt; &lt;a href=&quot;#titan&quot; >Titanium Mobile – A brief overview and introduction to a cross platform framework&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Jörgen Buder started developing assembler as a 12 year old, and have emerged trough eight bits to 64 bits, from assembler to Java, from desktop to realtime OS. Coming from embedded environments of nanotechnology he is today working with and being technical lead of the Purple Scout mobile initiative as well as lead developer to the scrum teams. Jörgen has only begun to reach out to the open scene of talks and presentations, but has a down to earth developer way of seeing things without losing perspective on the business that makes us tick. Jörgen is a high pace person that runs almost daily, is a hang-gliding pilot and loves to record music in the home studio.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>erikl</id>
        <fname>Erik</fname>
        <lname>Larsson</lname>
        <info>&lt;img src=&quot;images/erikl.jpg&quot; alt=&quot;erikl&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Erik Larsson's presentation:&lt;br /&gt; &lt;a href=&quot;#unmob&quot; >Understanding mobile design patterns&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Erik Larsson is co-founder of Plexical, a consultancy based in Gothenburg and Barcelona specialized in the design and development of mobile apps and advanced webapps.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>perd</id>
        <fname>Per</fname>
        <lname>Daleskog</lname>
        <info>&lt;img src=&quot;images/pdaleskog.jpg&quot; alt=&quot;pard&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Per Daleskog's presentation:&lt;br /&gt; &lt;a href=&quot;#mobweb&quot; >Mobil webbutveckling med HTML5, CSS3 och JavaScript&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Per Daleskog jobbar som mobilutvecklare. Efter ca 10 års erfarenhet av mobilutveckling på olika större konsultbolag och för olika kunders räkning bestämde han sig i slutet av 2010 att starta upp ett företag som skulle fokusera på det han brinner för mest, mobila lösningar och framförallt att hjälpa andra med detta. Han har jobbat med applikationsutveckling på olika plattformar från Symbian, Java ME, iOS och Android för att på senare år framförallt fokusera på mobil webbutveckling. Per är bland annat en av utvecklarna bakom &lt;a href=&quot;https://m.svenskaspel.se/&quot; target=&quot;_blank&quot;>m.svenskaspel.se&lt;/a&gt; som han varit med och utvecklat från första versionen.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>henriks</id>
        <fname>Henrik</fname>
        <lname>Sjöström</lname>
        <info>&lt;img src=&quot;images/henriks.jpg&quot; alt=&quot;henriks&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Henrik Sjöstrand's presentation:&lt;br /&gt; &lt;a href=&quot;#lowl&quot; >Low Latency Messaging for Mobile Apps - Or When HTTP and Push Messages Are Simply Not Enough&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Henrik Sjöstrand is a mobile evangelist in the WebSphere team in IBM’s Software Group. He is based right here – in Gothenburg, Sweden. When not working he enjoys flying radio controlled helicopters and multicopters, preferably FPV style! He also has a bad habit of covering his house with 1-Wire sensors to monitor every single aspect of it.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>mattiasl</id>
        <fname>Mattias</fname>
        <lname>Larsson</lname>
        <info>&lt;img src=&quot;images/mattiasl.jpg&quot; alt=&quot;mattiasl&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Mattias Larsson's presentation:&lt;br /&gt; &lt;a href=&quot;#soyou&quot; >So you have the greatest idea for the Next Big Hit Windows Phone Game?&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;I work as a senior C# consultant for &lt;a href=&quot;http://www.diversify.se/&quot; target=&quot;_blank&quot;>Diversify&lt;/a&gt;in Malmö. My greatest interest is programming (on the Microsoft platforms, it was long ago I left Commodore 64… During 2011 I took it as a challenge to create a Windows Phone game. The result was &lt;a href=&quot;http://www.windowsphone.com/sv-se/apps/0486a9d0-003a-413d-adbe-8b5f274cc7bf&quot; target=&quot;_blank&quot;>“Badgers Rock”&lt;/a&gt;. Microsoft showed interest in the game and arranged a one-week competition on their Facebook site &lt;a href=&quot;http://www.facebook.com/wpswe&quot; target=&quot;_blank&quot;>“Windows Phone Sverige”&lt;/a&gt; where the winner got a Nokia Headset. I have learned a lot during the creation and have new stuff ongoing. I feel I have quite a bit to share with my fellow developers regarding making Windows Phone games using the XNA framework.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>jorgenb</id>
        <fname>Jörgen</fname>
        <lname>Bengtsson</lname>
        <info>&lt;img src=&quot;images/jorgenb.png&quot; alt=&quot;jorgenb&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Jörgen Bengtsson's presentation:&lt;br /&gt; &lt;a href=&quot;#mobcross&quot; >Mobile cross-platform development with JQuery Mobile&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Jörgen Bengtsson (and &lt;a href=&quot;#johanh&quot; >Johan Holm&lt;/a&gt;) are two of Sigma’s lead developers for mobile web applications. We are well versed in many different technologies like PhoneGap and JQuery Mobile. During the last years we have worked on a number of mobile applications development projects for customers like Liseberg, VGR, and Ascom to name a few.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>johanh</id>
        <fname>Johan</fname>
        <lname>Holm</lname>
        <info>&lt;img src=&quot;images/johan_holm.jpg&quot; alt=&quot;johanh&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Johan Holm's presentation:&lt;br /&gt; &lt;a href=&quot;#mobcross&quot; >Mobile cross-platform development with JQuery Mobile&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Johan Holm (and &lt;a href=&quot;#jorgenb&quot; >Jörgen Bengtsson&lt;/a&gt;) are two of Sigma’s lead developers for mobile web applications. We are well versed in many different technologies like PhoneGap and JQuery Mobile. During the last years we have worked on a number of mobile applications development projects for customers like Liseberg, VGR, and Ascom to name a few.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>jonatan</id>
        <fname>Jonatan</fname>
        <lname>Redvik</lname>
        <info>&lt;img src=&quot;images/jonatan.jpg&quot; alt=&quot;jonatan&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Jonatan Redvik's presentation:&lt;br /&gt; &lt;a href=&quot;#sana&quot; >Så når du ut med din app&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Jonatan var tidigare chef på Ericsson för mjukvaruutveckling av 3G/4G. I början av 2011 startade han Appland, som idag sysselsätter 9 personer och samarbetar med teleoperatörerna TeliaSonera och Tre.&lt;br /&gt;
		</info>
    </speaker>
    
    <speaker>
		<id>erwan</id>
        <fname>Erwan</fname>
        <lname>Paccard</lname>
        <info>&lt;img src=&quot;images/erwan.jpg&quot; alt=&quot;jonatan&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Erwan Paccard's presentation:&lt;br /&gt; &lt;a href=&quot;#top11&quot; >Keynote: Top 11 Trends for Enterprise Mobile&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Erwan is a senior product manager for the IBM mobile portfolio with 14 years of experience. Erwan is an engineer in computer science and holds a masters degree in technology management from the EM Lyon business school&lt;br /&gt;
		</info>
    </speaker>
    
   <speaker>
		<id>mhansson</id>
        <fname>Mattias</fname>
        <lname>Hansson</lname>
        <info>
            &lt;img src=&quot;images/mattias_web.jpg&quot; alt=&quot;mhansson&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Mattias Hansson's presentations:&lt;br /&gt;&lt;a href=&quot;#vinnare&quot;&gt;Bli en vinnare på företagsmarknaden med dina appar!&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;
            Mattias Hansson är en serieentreprenör som under de senaste 10 åren startat upp flertalet bolag inom IT och Telekom. Bland företagen märks:
            &lt;br /&gt;
            &lt;ul&gt;
            &lt;li&gt;OptiMobile AB &lt;a href=&quot;http://www.optimobile.se/&quot; target=&quot;_blank&quot;&gt;www.optimobile.se&lt;/a&gt; som är pionjären inom mjukvara/appar för mobil IP-telefoni med kunder som SingTel, Ericsson och Nokia Siemens.&lt;/li&gt;
            &lt;li&gt;OptiCaller Software AB &lt;a href=&quot;http://www.opticaller.com/&quot; target=&quot;_blank&quot;&gt;www.opticaller.com&lt;/a&gt; som är världsledande inom mjukvara/appar inom mobil växel med unik samtalsoptimering.&lt;/li&gt;
            &lt;li&gt;InnoTel AB är en ny innovativ operatör som siktar på att bli vad Skype och Rebtel är på konsumentmarknaden fast på företagsmarknaden.&lt;/li&gt;
            &lt;li&gt;AppBooster Sweden AB &lt;a href=&quot;http://www.app-booster.com/&quot; target=&quot;_blank&quot;&gt;www.app-booster.com&lt;/a&gt; har utvecklat ett revolutionerande app management/distributionssystem som förenklar hantering av appar.&lt;/li&gt;
            &lt;/ul&gt;
            &lt;br /&gt;
            Mattias Hansson har innan dess arbetet på Telias Riskkapitalbolag ”Telia Business Innovation” och där varit med och startat upp företag på bra innovationer från Telias verksamhet.
            &lt;br /&gt;
            &lt;br /&gt;Mattias Hansson är utbildad Civilingenjör från Chalmers och har också en Internationell MBA examen. Mattias är delaktig i framtagande av 7st patent.
		</info>
    </speaker>
    
    <!-- Reserve speakers-->
    
    <!--
    <speaker>
		<id>andreask</id>
        <fname>Andreas</fname>
        <lname>Kviby</lname>
        <info>&lt;img src=&quot;images/andreaskviby.jpg&quot; alt=&quot;andreask&quot;/&gt;&lt;br /&gt;
            &lt;br /&gt;Andreas Kviby's presentation:&lt;br /&gt; &lt;a href=&quot;#spelapp&quot; >Spel och apputveckling Cross plattform&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Andreas Kviby is a true geek that has been developing solutions with Microsoft technology since 1995 for the web and since a couple of years he is dedicated to mobile development with Corona SDK and the language LUA. He is now the CEO of 10FINGERS with more than 15 employees working with mobile development only. Andreas has been responsible for some huge projects during his career and is now responsible for the largest iPad educational project in Sweden. You can read more about Andreas and his company 10FINGERS on the website &lt;a href=&quot;http://www.10fingers.se/&quot; target=&quot;_blank&quot;>www.10fingers.se.&lt;/a&gt;&lt;br /&gt;
		</info>
    </speaker>
	-->
    
</speakers>