<?xml version="1.0"?>
<!DOCTYPE sponsors [
    <!ELEMENT sponsors (sponsor*)>
        <!ELEMENT sponsor (id, company, info)>
            <!ELEMENT id (#PCDATA)>
            <!ELEMENT company (#PCDATA)>
            <!ELEMENT info (#PCDATA)>
]>

<sponsors>
    
    <sponsor>
        <id>microsoft</id>
        <company>Microsoft</company>
        <info>
            &lt;a href=&quot;http://www.microsoft.com/sv-se/default.aspx&quot;target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/microsoft.jpg&quot; alt=&quot;microsoft&quot;/&gt;&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;&lt;br /&gt;At Microsoft, we’re motivated and inspired every day by how our customers use our software to find creative solutions to business problems, develop breakthrough ideas, and stay connected to what’s most important to them.&lt;br /&gt;
            &lt;br /&gt;We run our business in much the same way, and believe our eight business divisions offer the greatest potential to serve our customers. They are:&lt;br /&gt;

            &lt;br /&gt;Online Services Division: Microsoft’s search, portal, advertising and personal communications services, including online information offerings such as Bing and the MSN portals and channels.&lt;br /&gt;
            &lt;br /&gt;Server and Tools Business: Microsoft infrastructure software, developer tools and cloud platform, including products such as Windows Server, SQL Server, Visual Studio, System Center and the Windows Azure Platform.&lt;br /&gt;
            &lt;br /&gt;Microsoft Business Solutions: A portfolio of Microsoft Dynamics products and services, as well as Microsoft Health Solutions.&lt;br /&gt;
            &lt;br /&gt;Microsoft Office Division: Productivity products and services, including Office, Exchange, SharePoint, Lync, Project, Visio, and Microsoft’s speech technology investments.&lt;br /&gt;
            &lt;br /&gt;Interactive Entertainment Business: Key entertainment experiences that span gaming, music and video across multiple screens, including Xbox 360, Xbox LIVE, the controller-free Kinect for Xbox 360, Zune Music and Video, and Mediaroom, as well as PC and mobile interactive entertainment.&lt;br /&gt;
            &lt;br /&gt;Windows Phone Division: Microsoft software and services for Windows Phones worldwide.&lt;br /&gt;
            &lt;br /&gt;Windows and Windows Live Division: All Windows businesses, including Windows, Windows Live and Internet Explorer.&lt;br /&gt;
            &lt;br /&gt;Skype: A division of Microsoft, transforming communications for computers, mobile devices and the connected living room.&lt;br /&gt;

            &lt;br /&gt;We are committed long term to the mission of helping our customers realize their full potential. Just as we constantly update and improve our products, we want to continually evolve our company to be in the best position to accelerate new technologies as they emerge and to better serve our customers.&lt;br /&gt;
            &lt;br /&gt;&lt;a href=&quot;http://www.microsoft.se&quot; target=&quot;_blank&quot;>http://www.microsoft.se&lt;/a&gt;&lt;br /&gt;

        </info>
    </sponsor>

    <sponsor>
        <id>informator</id>
        <company>Informator</company>
        <info>
            &lt;a href=&quot;http://www.informator.se&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/informator.gif&quot; alt=&quot;informator&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;Rätt använda IT-lösningar automatiserar rutinmässiga arbetsuppgifter och minskar arbetsbördan och risken för fel. Det ger minskade kostnader och ökande effektivitetsvinster.&lt;br /&gt;
            &lt;br /&gt;Men många organisationer utnyttjar bara en bråkdel av kraften i sina IT-lösningar. För att frigöra de stora möjligheter som dagens system och applikationer medför, behövs kunskap och kompetens.&lt;br /&gt;
            &lt;br /&gt;&lt;h2&gt;Affärsorienterad kompetensutveckling&lt;/h2&gt;
            &lt;br /&gt;Informator arbetar med kunskapsöverföring som hjälper organisationer och individer att utveckla rätt kompetens. Vi ser det som en del av våra kunders verksamhets- och affärsutveckling. Syftet med ny kunskap är att organisationen ska fungera bättre. Det åstadkommer vi genom att utbilda en individ i taget.&lt;br /&gt;
            &lt;br /&gt;När en individ utvecklas, får han/hon ut mer av sitt arbete och företaget får ut mer av varje medarbetare. Det leder till ökad lönsamhet, vilket ger utrymme för ännu mer utveckling.&lt;br /&gt;
            &lt;br /&gt;Den här goda cirkeln börjar med kunskap. Att koppla kunskapsöverföring och kompetensutveckling till affärsnytta är därför en viktig del av vårt sätt att arbeta.&lt;br /&gt;
            &lt;br /&gt;Utifrån ett affärsperspektiv analyserar vi nuvarande och framtida kunskapsbehov. Vi rekommenderar vilka utbildningsinsatser som behövs. Efter genomförd utbildning gör vi uppföljningar som säkerställer att kunskapsmålen är uppnådda&lt;br /&gt;

        </info>
    </sponsor>

    <sponsor>
        <id>appland</id>
        <company>Appland</company>
        <info>
            &lt;a href=&quot;http://www.appland.se/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/appland.png&quot; alt=&quot;appland&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;&lt;h2&gt;Marknadsplats för Svenska Android-appar&lt;/h2&gt;&lt;br /&gt;&lt;br /&gt;Alla appar är kvalitetskontrollerade så du kan känna dig trygg när du laddar ner den till din telefon. Appland innehåller både gratis- och betalappar. Väljer du att köpa en app så läggs kostnaden på din mobilräkning eller dras från ditt kontantkort, du behöver alltså inte registrera dig eller använda kreditkort. För att kunna ladda ner gratis- eller betalappar måste du först installera Appland i din smartphone.&lt;br /&gt;

        </info>
    </sponsor>
   
    <sponsor>
        <id>nokia</id>
        <company>Nokia</company>
        <info>
            &lt;a href=&quot;http://www.nokia.com/se-sv/&quot;target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/nokia.png&quot;alt=&quot;nokia&quot;/&gt;&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;Nokia är en världsledande aktör inom mobil kommunikation med produkter som har blivit en naturlig del av människors liv världen över.&lt;br /&gt;
            &lt;br /&gt;Varje dag använder mer än 1,3 miljarder människor sin Nokia för att fånga och dela med sig av upplevelser, få tillgång till information,
            hitta rätt eller bara prata med andra människor. Nokias teknologi- och designinnovationer har gjort varumärket till ett av världens mest kända.&lt;br /&gt;
            &lt;br /&gt;För mer information, besök &lt;a href=&quot;http://www.nokia.se/om-nokia&quot; target=&quot;_blank&quot;>http://www.nokia.se/om-nokia&lt;/a&gt;&lt;br /&gt;
        </info>
    </sponsor>
    
    <sponsor>
        <id>ibm</id>
        <company>IBM</company>
        <info>
            &lt;a href=&quot;http://www.ibm.com/se/sv/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/ibm_pos_blue.jpg&quot;alt=&quot;ibm&quot;/&gt;&lt;/a&gt;&lt;br /&gt;
            &lt;br /&gt;&lt;br /&gt;IBM Mobile Foundation är en komplett lösning för att bygga plattformsoberoende mobil-applikationer samt hantera både dina applikationer och mobila enheter. Med hjälp av IBM Worklight-modulen bygger du snabbt, enkelt och kostnadseffektivt plattformsoberoende mobil-applikationer baserat på öppna standarder såsom HTML5 och JavaScript. Cast Iron-modulen låter dig enkelt koppla dessa applikationer till dina egna affärssystem eller tjänster på Internet och med hjälp av Endpoint Manager for Mobile Devices får du full kontroll över dina mobila enheter i verksamheten. Varje modul fungerar även fristående från övriga så du kan t.ex. välja att använda enbart IBM Worklight om du bara vill bygga plattformsoberoende mobil-applikationer.&lt;br /&gt;
            &lt;br /&gt;Läs mer om IBM Mobile Foundation &lt;a href=&quot;http://www-01.ibm.com/software/solutions/mobile-enterprise/build/&quot; target=&quot;_blank&quot;>här&lt;/a&gt;&lt;br /&gt;

        </info>
    </sponsor>
    
    <sponsor>
        <id>ps</id>
        <company>Purple Scout</company>
        <info>
            &lt;a href=&quot;http://www.purplescout.com/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/ps.jpg&quot;alt=&quot;ps&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;Purple Scout is actively involved in developing apps with Titanium; making us uniquely positioned to provide quality, real world, practical and hands-on training. We are passionate about inspiring our customers to learn and go out into the wild building apps to ignite the world.&lt;br /&gt;
            &lt;br /&gt;The company was founded in 2004 in Malmö, Sweden with offices in Gothenburg, Stockholm, and has experienced exceptional growth ever since, providing training throughout Europe.&lt;br /&gt;
        </info>
    </sponsor>
    
    <sponsor>
        <id>af</id>
        <company>ÅF</company>
        <info>
            &lt;a href=&quot;http://www.afconsult.com/sv/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/af.jpg&quot;alt=&quot;af&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;
            &lt;h2&gt;Nytänkande med erfarenhet&lt;/h2&gt;&lt;br /&gt;&lt;br /&gt;ÅF är ett ledande teknikkonsultföretag med kunskap som vilar på hundraårig erfarenhet.  ÅF kombinerar avancerat ingenjörskunnande, förnyelse och modernaste teknik med mångårig tradition och förankring i svensk industri. Få teknikkonsulter har idag samma bredd och resurser.&lt;br /&gt;
            &lt;br /&gt;Genom vår breda kunskap får vi förmånen att vara en resurs i en rad framtidsinriktade uppdrag inom de mest skiftande områden för både stora och små företag. Det kan vara allt från utveckling av mobiltelefoni till projektering av kompletta energianläggningar.&lt;br /&gt;
            &lt;br /&gt;ÅF har idag cirka 4 500 medarbetare. Vår bas finns i Europa, men vår verksamhet och våra kunder finns i hela världen.&lt;br /&gt;
            &lt;br /&gt;Vill du bli en av oss? Läs mer på &lt;a href=&quot;http://afconsult.com/sv/Jobb/&quot; target=&quot;_blank&quot;>http://afconsult.com/sv/Jobb/&lt;/a&gt;&lt;br /&gt;

        </info>
    </sponsor>
    
    <sponsor>
        <id>adecco</id>
        <company>Adecco</company>
        <info>
            &lt;a href=&quot;http://www.adecco.se/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/adecco.jpg&quot; alt=&quot;adecco&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;Adecco IT Konsult är en nystartad IT-konsultverksamhet inom Adeccokoncernen. Vi bygger upp en platt organisation fokuserad kring värdeskapande lösningar och expertkompetens.
            Ny­fikenhet, kompetens och framkant är nyckelord för Adecco IT Konsult och vi drivs framåt av vårt gemensamma intresse för nya spännande tekniker och lösningar. Våra kunder ­finns främst inom områden som automotive, telekom och logistik. Vi utvecklar våra kunders verksamhet som experter inom Java- och .NET-utveckling, mobila applikationer, systemarkitektur, projektledning, kravställning, databaser, testledning, inbyggda system, applikationssäkerhet och utbildning.&lt;br /&gt;
            &lt;br /&gt;Vill du bli en av oss? Du är välkommen att höra av dig till Hesho Ahmad, Rekryteringsansvarig på telefon: 031 – 7207204 eller skicka ett mail till: hesho.ahmad@adecco.se. Varmt välkommen!&lt;br /&gt;

        </info>
    </sponsor>
    
    <sponsor>
        <id>appspotr</id>
        <company>AppSpotr</company>
        <info>
            &lt;a href=&quot;https://www.appspotr.com/&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/appspotr.png&quot;alt=&quot;appspotr&quot;/&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;With AppSpotr you build your own iPhone and Android app in less than 5 minutes! AppSpotr is a fully hosted web tool for creating and maintaining native apps for both iPhone and Android. Comes with the AppSpotr Viewer app, letting you preview your native apps before publishing.&lt;br /&gt;
            &lt;br /&gt;Anytime, anywhere you can update your app for everyday changes. No need for end user app updates. It´s all hosted and automatic.&lt;br /&gt;
            &lt;br /&gt;&lt;a href=&quot;https://www.appspotr.com/&quot; target=&quot;_blank&quot;>www.appspotr.com&lt;/a&gt;&lt;br /&gt;

        </info>
    </sponsor>
   

</sponsors>


